### ISSUE TITLE
Text not fitting in item box [BUG]

### ISSUE THREAD

**Issue by ItsOliB** [vipexee/QB-Inventory-Re-Design#1]
### Summary

The text of the item isn't fitting in the box 

### Reproduction

1. Buy an item from a store
2. Use it
3. It then doesn't fit into the box

### Expected behavior

The text is meant to fit in the box and or show in the box or display at all.

### Actual behavior

Doesn't display the text of the item or it doesn't show it in the box

![oEry6uN](https://user-images.githubusercontent.com/120398063/214707480-60bd1b66-6c59-4c7b-9a94-f36178aedd9e.jpeg)
![kJRE52D](https://user-images.githubusercontent.com/120398063/214707483-1948174a-3d97-4012-90e3-949ec5aac1d4.jpeg)

### Last Updated

Very recently

### Custom Resources

Nothing that would conflict with it

### Resource Rename

No

**Comment by vipexv** [comment]
What Resolution are you playing on?

**Comment by ItsOliB** [comment]
> What Resolution are you playing on?

I'm playing on 2560 x 1440

**Comment by vipexv** [comment]
It's due to the resolution, it doesn't scale at all, ill fix that soon since i'm planning on making a new version of this either way, but you can add CSS code to make a max width for specific resolutions.
